apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: lizzoslunch
  labels:
    #pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
spec: {}
status: {}